#!/usr/bin/python3
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import print_function

from plano import *

from datetime import date
from requests import Session

list_names = "qpid-dev", "qpid-users", "qpid-proton"
start_dates = (2006, 8), (2007, 10), (2012, 8)

# http://mail-archives.apache.org/mod_mbox/qpid-dev/201510.mbox

make_dir("data")

with Session() as session:
    for i, list_name in enumerate(list_names):
        start_year, start_month = start_dates[i]
        today = date.today()

        # Remove the latest mbox file; it may be partial
        # XXX Should remove latest *two*
        
        file_name = "{}-{}{:02}.mbox".format(list_name, today.year, today.month)
        remove(join("data", file_name))
        
        for year in range(start_year, today.year + 1):
            print("#", list_name, year)

            for month in range(1, 13):
                if year == start_year and month < start_month:
                    continue

                if year == today.year and month > today.month:
                    continue

                file_name = "{}-{}{:02}.mbox"
                file_name = file_name.format(list_name, year, month)

                file = join("data", file_name)

                if exists(file):
                    notice("Already fetched {}", file)
                    continue
                
                url = "http://mail-archives.apache.org/mod_mbox/{}/{}{:02}.mbox"
                url = url.format(list_name, year, month)

                notice("Fetching {}", url)
        
                response = session.get(url)

                if response.status_code != 200:
                    warn("HTTP request failed: {}", response.status_code)
                    continue

                with open(file, 'wb') as f:
                    for chunk in response.iter_content(4096):
                        f.write(chunk)
